# Generated by Django 5.2.17 on 2026-08-12 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Human-readable case reference, e.g. CMP-2026-00184.', max_length=32, unique=True)),
                ('source', models.CharField(choices=[('SELF', 'Filed by the employee'), ('HR_FOR_EMPLOYEE', 'Filed by HR on behalf of an employee'), ('HR_FOR_COMPANY', 'Filed by HR on behalf of the company')], max_length=32)),
                ('subject_type', models.CharField(choices=[('GENERAL', 'General grievance'), ('EMPLOYEE', 'About an employee')], max_length=16)),
                ('complaint_type', models.CharField(choices=[('SEXUAL_ASSAULT', 'Sexual assault'), ('SEXUAL_HARASSMENT', 'Sexual harassment'), ('HOSTILE_WORK_ENVIRONMENT', 'Hostile work environment'), ('THEFT', 'Theft'), ('UNSUSTAINABLE_WORKLOAD', 'Unsustainable workload'), ('OTHERS', 'Others')], max_length=32)),
                ('complaint_type_note', models.TextField(blank=True, help_text='Free text describing an OTHERS complaint. Stored for the case record and reporting. Never used as a filter dimension.')),
                ('frequency', models.CharField(blank=True, choices=[('ONE_TIME', 'One time'), ('REPEAT_BEHAVIOR', 'Repeat behaviour')], max_length=16)),
                ('occurrence_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('HR', 'HR only'), ('LINE_MANAGER', 'Line manager only'), ('BOTH', 'HR and line manager')], db_index=True, help_text='Effective visibility, after any intake override.', max_length=16)),
                ('visibility_requested', models.CharField(choices=[('HR', 'HR only'), ('LINE_MANAGER', 'Line manager only'), ('BOTH', 'HR and line manager')], help_text='What the complainant actually selected. Differs from `visibility` when the complaint is about their own line manager and was forced to HR. Audit needs the original choice.', max_length=16)),
                ('state', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_INVESTIGATION', 'Under investigation'), ('AWAITING_DECISION', 'Awaiting decision'), ('RESOLVED', 'Resolved'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='SUBMITTED', max_length=32)),
                ('due_date', models.DateField(blank=True, help_text='Set by HR when an investigator is appointed. Null before that.', null=True)),
                ('complainant_identity_released', models.BooleanField(default=False, help_text='The respondent sees the allegation but not who filed it, unless HR explicitly releases the identity.')),
                ('complainant_identity_released_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('complainant', models.ForeignKey(blank=True, help_text='Null only when HR files on behalf of the company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_as_complainant', to='directory.employee')),
                ('complainant_identity_released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('filed_by', models.ForeignKey(help_text='Whoever submitted the form. Equals complainant unless HR filed it.', on_delete=django.db.models.deletion.PROTECT, related_name='complaints_filed', to='directory.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organisation')),
                ('respondent', models.ForeignKey(blank=True, help_text='Required when subject_type is EMPLOYEE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_as_respondent', to='directory.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('withdrawal_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComplaintEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('FILED', 'Complaint filed'), ('VIEWED', 'Complaint viewed'), ('VISIBILITY_OVERRIDDEN', 'Visibility overridden at intake'), ('ORPHAN_FALLBACK', 'Fell back to HR visibility'), ('INVESTIGATOR_APPOINTED', 'Investigator appointed'), ('COLLABORATOR_INVITED', 'Collaborator invited'), ('COLLABORATOR_REMOVED', 'Collaborator removed'), ('INFORMATION_REQUESTED', 'Information requested'), ('INFORMATION_RECEIVED', 'Information received'), ('MEETING_RECORDED', 'Meeting recorded'), ('ATTACHMENT_ADDED', 'Attachment added'), ('IDENTITY_RELEASED', 'Complainant identity released'), ('REPORT_SUBMITTED', 'Investigation report submitted'), ('WITHDRAWAL_REQUESTED', 'Withdrawal requested'), ('WITHDRAWN', 'Complaint withdrawn'), ('RESOLVED', 'Complaint resolved and closed'), ('REOPENED', 'Complaint reopened'), ('DELETE_ATTEMPTED', 'Deletion attempted'), ('DELETED', 'Complaint deleted')], db_index=True, max_length=32)),
                ('from_state', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_INVESTIGATION', 'Under investigation'), ('AWAITING_DECISION', 'Awaiting decision'), ('RESOLVED', 'Resolved'), ('WITHDRAWN', 'Withdrawn')], max_length=32)),
                ('to_state', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_INVESTIGATION', 'Under investigation'), ('AWAITING_DECISION', 'Awaiting decision'), ('RESOLVED', 'Resolved'), ('WITHDRAWN', 'Withdrawn')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='grievances.complaint')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='ComplaintWitness',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('witness_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPARTMENT', 'Department'), ('LINE_MANAGER', 'Line manager')], max_length=16)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='grievances.complaint')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.employee')),
            ],
            options={
                'ordering': ('requested_at',),
            },
        ),
        migrations.CreateModel(
            name='InformationResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='grievances.informationrequest')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.employee')),
            ],
            options={
                'ordering': ('responded_at',),
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveIntegerField(default=1)),
                ('lead_is_hr', models.BooleanField(default=False, help_text='True when HR assigned the case to themselves.')),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('REPORT_SUBMITTED', 'Report submitted')], default='IN_PROGRESS', max_length=32)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='grievances.complaint')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('lead', models.ForeignKey(help_text='One lead per case. May be the HR user who triaged it.', on_delete=django.db.models.deletion.PROTECT, related_name='investigations_led', to='directory.employee')),
                ('report_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
            ],
            options={
                'ordering': ('complaint', 'round'),
            },
        ),
        migrations.AddField(
            model_name='informationrequest',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='grievances.investigation'),
        ),
        migrations.CreateModel(
            name='InvestigationCollaborator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('COMPLAINANT', 'Complainant'), ('RESPONDENT', 'Respondent'), ('WITNESS', 'Witness'), ('OTHER', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('DECLINED', 'Declined'), ('REMOVED', 'Removed')], default='INVITED', max_length=16)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.employee')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='grievances.investigation')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
            ],
        ),
        migrations.AddField(
            model_name='informationrequest',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='grievances.investigationcollaborator'),
        ),
        migrations.CreateModel(
            name='InvestigationMeeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_date', models.DateField()),
                ('findings', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to='grievances.investigationcollaborator')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='grievances.investigation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.employee')),
            ],
            options={
                'ordering': ('-meeting_date',),
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.employee')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grievances.investigation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PIPPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pip_plans', to='directory.employee')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='PIPFollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('TWO_WEEK_CHECKIN', 'Two week check-in'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=32)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('pip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='grievances.pipplan')),
            ],
            options={
                'ordering': ('scheduled_date',),
            },
        ),
        migrations.CreateModel(
            name='PIPTrainingAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to='grievances.pipplan')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.training')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('SUBSTANTIATED', 'Substantiated'), ('UNSUBSTANTIATED', 'Unsubstantiated'), ('PARTIALLY_SUBSTANTIATED', 'Partially substantiated'), ('INCONCLUSIVE', 'Inconclusive'), ('WITHDRAWN_BY_COMPLAINANT', 'Withdrawn by complainant'), ('NO_FURTHER_ACTION_REQUIRED', 'No further action required')], max_length=32)),
                ('resolution_type', models.CharField(choices=[('FORMAL', 'Formal resolution'), ('INFORMAL', 'Informal resolution'), ('NO_RESOLUTION_REQUIRED', 'No resolution required')], max_length=32)),
                ('formal_resolution_type', models.CharField(blank=True, choices=[('FIRST_WRITTEN_WARNING', 'First written warning'), ('SECOND_WRITTEN_WARNING', 'Second written warning'), ('FINAL_WRITTEN_WARNING', 'Final written warning'), ('SUSPENSION', 'Suspension'), ('DISMISSAL', 'Dismissal'), ('OTHERS', 'Others')], max_length=32)),
                ('informal_resolution_type', models.CharField(blank=True, choices=[('VERBAL_WARNING', 'Verbal warning'), ('COACHING', 'Coaching'), ('MEDIATION', 'Mediation'), ('NO_ACTION_RESOLVED_WITHOUT_FORMAL_RECORD', 'No action (resolved without formal record)'), ('OTHERS', 'Others')], max_length=64)),
                ('resolution_note', models.TextField(blank=True, help_text='Required when either sub-type is OTHERS.')),
                ('decision_notes', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='grievances.complaint')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='directory.employee')),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='grievances.investigation')),
            ],
            options={
                'ordering': ('-decided_at',),
            },
        ),
        migrations.AddField(
            model_name='pipplan',
            name='resolution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pip_plan', to='grievances.resolution'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(upload_to='grievances/%Y/%m/')),
                ('original_filename', models.CharField(max_length=512)),
                ('content_type_header', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.employee')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='grievances__content_4c11c4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['organisation', 'state'], name='grievances__organis_a40215_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['organisation', 'visibility'], name='grievances__organis_dc2773_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complainant', 'state'], name='grievances__complai_112dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['respondent', 'state'], name='grievances__respond_2a0b43_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('respondent__isnull', False), ('subject_type', 'EMPLOYEE')), models.Q(('respondent__isnull', True), ('subject_type', 'GENERAL')), _connector='OR'), name='complaint_respondent_matches_subject_type'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('respondent__isnull', True), ('complainant__isnull', True), models.Q(('respondent', models.F('complainant')), _negated=True), _connector='OR'), name='complaint_respondent_is_not_complainant'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frequency', 'REPEAT_BEHAVIOR'), _negated=True), ('occurrence_count__isnull', False), _connector='OR'), name='complaint_repeat_requires_occurrence_count'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('complaint_type', 'OTHERS'), _negated=True), models.Q(('complaint_type_note', ''), _negated=True), _connector='OR'), name='complaint_others_requires_note'),
        ),
        migrations.AddIndex(
            model_name='complaintevent',
            index=models.Index(fields=['complaint', '-occurred_at'], name='grievances__complai_5b066b_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaintwitness',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('witness_type', 'EMPLOYEE')), models.Q(('department__isnull', False), ('witness_type', 'DEPARTMENT')), ('witness_type', 'LINE_MANAGER'), _connector='OR'), name='witness_reference_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='investigation',
            constraint=models.UniqueConstraint(fields=('complaint', 'round'), name='uniq_investigation_round_per_complaint'),
        ),
        migrations.AddConstraint(
            model_name='investigationcollaborator',
            constraint=models.UniqueConstraint(fields=('investigation', 'employee'), name='uniq_collaborator_per_investigation'),
        ),
        migrations.AddConstraint(
            model_name='resolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('formal_resolution_type__gt', ''), ('informal_resolution_type', ''), ('resolution_type', 'FORMAL')), models.Q(('formal_resolution_type', ''), ('informal_resolution_type__gt', ''), ('resolution_type', 'INFORMAL')), models.Q(('formal_resolution_type', ''), ('informal_resolution_type', ''), ('resolution_type', 'NO_RESOLUTION_REQUIRED')), _connector='OR'), name='resolution_subtype_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='resolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('formal_resolution_type', 'OTHERS'), ('informal_resolution_type', 'OTHERS'), _connector='OR', _negated=True), models.Q(('resolution_note', ''), _negated=True), _connector='OR'), name='resolution_others_requires_note'),
        ),
        migrations.AddConstraint(
            model_name='pipplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='pip_end_after_start'),
        ),
    ]
