# Generated by Django 5.2.17 on 2026-08-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('directory', '0001_initial'),
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reference',
            field=models.CharField(db_index=True, help_text='Human-readable case reference, e.g. CMP-2026-00184. Unique within an organisation, not globally -- each tenant numbers from 1.', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('organisation', 'reference'), name='uniq_reference_per_org'),
        ),
        migrations.AddField(
            model_name='referencecounter',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_counters', to='core.organisation'),
        ),
        migrations.AddConstraint(
            model_name='referencecounter',
            constraint=models.UniqueConstraint(fields=('organisation', 'year'), name='uniq_reference_counter_per_year'),
        ),
    ]
